name: ai_exercise_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State Manajemen & Routing
  get: ^4.7.2

  # Firebase
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7

  #Local Storage
  shared_preferences: ^2.5.3
  path: ^1.9.1
  path_provider: ^2.1.5

  #Camera & ML Kit
  camera: ^0.11.1
  google_mlkit_pose_detection:
    ^0.14.0

    # UI & Visualization
  flutter_svg: ^2.0.9
  fl_chart: ^0.71.0
  lottie: ^3.3.1

  # Utilities
  intl: ^0.20.2
  image_gallery_saver: ^2.0.3
  share_plus: ^11.0.0
  screenshot: ^3.0.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #Testing
  build_runner: ^2.4.15
  firebase_auth_mocks: ^0.14.1
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
