// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3cgQOvHYXxQZk0xVCDgPe_81tnQIO_Y',
    appId: '1:989068302280:web:d77416fb466bd8b146d2fd',
    messagingSenderId: '989068302280',
    projectId: 'ai-exercise-tracker',
    authDomain: 'ai-exercise-tracker.firebaseapp.com',
    storageBucket: 'ai-exercise-tracker.firebasestorage.app',
    measurementId: 'G-91BXJGKH19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKh4ALa8m4jrQ3pG7_S2jBne0NgsWG7eU',
    appId: '1:989068302280:android:66a326f497af99ee46d2fd',
    messagingSenderId: '989068302280',
    projectId: 'ai-exercise-tracker',
    storageBucket: 'ai-exercise-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hS7lcy4I3mjW5f58F_mF103g8Gpi86w',
    appId: '1:989068302280:ios:864b6d217d72f41246d2fd',
    messagingSenderId: '989068302280',
    projectId: 'ai-exercise-tracker',
    storageBucket: 'ai-exercise-tracker.firebasestorage.app',
    iosBundleId: 'com.example.aiExerciseTracker',
  );
}
